### PR TITLE
wip allow for op suffixes

### PR DESCRIPTION
**Pull request by KristofferC**
Ref https://github.com/JuliaLang/julia/pull/22089#event-1257872465

### CODE REVIEW

**Comment by KristofferC** [comment]
@ZacLN As discussed with @Keno, there are two ways to handle this.

One is either as in this PR, to have a custom "operator suffix" `kind` (I called it badly `SPEC_OP` here but we can fix name later) that we emit as a separate token after the standard operator.
The other is to effectively double the number of `kind`s such that each operator has an associated special operator. I think I like the way done in this PR more because it reduces the number of `kind`s and the code churn here, but perhaps there is a difference in how well it translates to the parsing code.

**Comment by ZacLN** [comment]
My intuition is that this is the better approach

**Comment by Keno** [comment]
@ZacLN @KristofferC Are we good with this approach? If so, shall we merge?

**Comment by ZacLN** [comment]
Can I have a think on how to implement it in cstparser first? I'll have a look this weekend

**Comment by Keno** [comment]
Bump!

**Comment by ZacLN** [comment]
Sorry for delay. 

Thoughts- this doesn't do the job properly. There's no ambiguity in these cases and no reliance on context (above what is known at the `Tokenize` level) so we should be returning a single `Token`.

Similarly, do the changes in v0.7 make use of dot operators unambiguous? i.e. should they be handled to return a single TOken at this level?

EDIT: Further thoughts: introduce an extra function call before emitting an operator that checks for suffixes and appends it to the `val` field + possibly add a Boolean field to `Token`/`RawToken` indicating its not a 'pure' operator?

**Comment by ZacLN** [comment]
An example for dotted operator handling handling
https://github.com/KristofferC/Tokenize.jl/pull/128

**Comment by Keno** [comment]
Superseded by #129

**Pull request closed without merging**
