### PR TITLE
#188, but fixed

### LINKED ISSUE #189: Tokenize 0.5.19 broke JuMPs formatting
https://github.com/jump-dev/JuMP.jl/issues/2673

A passing log is (Tokenize 0.5.18):

https://github.com/jump-dev/JuMP.jl/runs/3391118073

A failing log is (Tokenize 0.5.19):

https://github.com/jump-dev/JuMP.jl/runs/3416358585

Confirmed that the only difference between the two runs is the minor bump of tokenize, and verified this locally. It's also weird in that I can only reproduce on linux. Mac works fine.

```Julia
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [12aac903] BinaryBuilder v0.4.0
  [98e50ef6] JuliaFormatter v0.13.2
  [0796e94c] Tokenize v0.5.18

julia> using JuliaFormatter; format("src/lp_sensitivity.jl")
true

(@v1.6) pkg> add Tokenize@0.5.19
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [0796e94c] ↑ Tokenize v0.5.18 ⇒ v0.5.19
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [0796e94c] ↑ Tokenize v0.5.18 ⇒ v0.5.19
  Progress [========================================>]  3/3
  ? CSTParser
  ? JuliaFormatter
1 dependency successfully precompiled in 4 seconds (64 already precompiled)
2 dependencies failed but may be precompilable after restarting julia

julia> exit()
(base) parallels@parallels-Parallels-Virtual-Platform:~/.julia/dev/JuMP$ ~/julia-1.6
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [12aac903] BinaryBuilder v0.4.0
  [98e50ef6] JuliaFormatter v0.13.2
  [0796e94c] Tokenize v0.5.19

julia> using JuliaFormatter; format("src/lp_sensitivity.jl")
[ Info: Precompiling JuliaFormatter [98e50ef6-434e-11e9-1051-2b60c6c9e899]
ERROR: Parsing error for input occurred on line 419, offset: 79
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] format_text(text::String, style::DefaultStyle, opts::JuliaFormatter.Options)
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:322
  [3] #format_text#161
    @ ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:316 [inlined]
  [4] #format_text#160
    @ ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:310 [inlined]
  [5] format_file(filename::String; overwrite::Bool, verbose::Bool, format_markdown::Bool, format_options::Base.Iterators.Pairs{Symbol, Integer, NTuple{5, Symbol}, NamedTuple{(:short_to_long_function_def, :remove_extra_newlines, :margin, :always_for_in, :always_use_return), Tuple{Bool, Bool, Int64, Bool, Bool}}})
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:421
  [6] format(paths::Tuple{String}; options::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:528
  [7] format
    @ ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:504 [inlined]
  [8] #format#170
    @ ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:553 [inlined]
  [9] format(path::String)
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FlpTt/src/JuliaFormatter.jl:553
 [10] top-level scope
    @ REPL[2]:1
```

I'll try to narrow it down further

### PR DESCRIPTION
**Pull request by pfitzseb**
This fixes the `simple_hash` function introduced in #188. The new implementation just pushes all characters into an `Int128` (so `simple_hash("if") == 508` because `'f'-'a' == 05` and `'i'-'a' == 08`), which works fine because keywords are at most 10 characters long at the moment. 

Fixes https://github.com/JuliaLang/Tokenize.jl/issues/189.

### CODE REVIEW

**Comment by KristofferC** [comment]
Would it be easy to add a test that ensures this is ok?

**Comment by pfitzseb** [comment]
Added a test that goes over all lower-case ASCII strings up to length 5. Takes a minute or two, but that should be fine. Of course it doesn't really test correctness though... It did find a bug in my code, so that's good I guess :P

**Comment by KristofferC** [comment]
@odow, would it be possible for you to manually test this PR and see if this is ok w.r.t the issues you had with the earlier one?

**Comment by domluna** [comment]
I can update the compat for the formatter once this lands

**Comment by KristofferC** [comment]
I don't see how the compat for JuliaFormatter is related here (since the buggy PR got reverted and a new patch version tagged)

**Comment by domluna** [comment]
hmm maybe not required since if they update or fresh install it would get the more recent version of the dependency right?

**Comment by KristofferC** [comment]
Yes, and we should yank the buggy one for completeness sake.

**Comment by odow** [comment]
Confirmed that it works:
```Julia
julia> using JuliaFormatter

julia> format("src/lp_sensitivity.jl")
true

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [98e50ef6] JuliaFormatter v0.15.8
  [0796e94c] Tokenize v0.5.18 `https://github.com/JuliaLang/Tokenize.jl.git#load-time`
```

**Pull request merged**
