### PR TITLE
tweak `is_operator_start_char` to not use so heavily nested syntax

### PR DESCRIPTION
**Pull request by KristofferC**
Ref https://github.com/JuliaLang/JuliaSyntax.jl/issues/368

### CODE REVIEW

**Review by pfitzseb — APPROVED** [review]

**Comment by oscardssmith** [comment]
wouldn't it be better to use `searchsortedfirst` to prevent the allocation? (although that is a fairly minor difference)

**Comment by KristofferC** [comment]
What allocation?

**Comment by oscardssmith** [comment]
`searchsorted` allocates an array for it's return value.

**Comment by KristofferC** [comment]
Are you sure?

**Comment by oscardssmith** [comment]
oh, never mind. I remembered incorrectly.

**Pull request merged**
