### PR TITLE
fix float lexing

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by ZacLN** [comment]
Related, I'm not quite sure what `accept(l, "o")` does on lines 586, 591 and 596

**Comment by ZacLN** [comment]
this needs fixes, hold up

**Comment by KristofferC** [comment]
If stuff doesn't seem to make sense, it's probably because they don't.

**Comment by KristofferC** [comment]
I didn't really know what I was doing when I wrote this...

**Comment by ZacLN** [comment]
Alright, I've taken them out. Doesn't look like it impacted anything in my parser tests

**Pull request merged**
