### PR TITLE
use where as operator, fix typo

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by KristofferC** [comment]
Is `where` really an operator? I'm not sure what I would call it... You can assign to it like a normal variable without changing the way `where` works in function definitions.

**Comment by ZacLN** [comment]
Yeah it definitely sits in the middle, but it get's parsed with a set (if strange) precedence along with other operators and I'm guessing that most of it's use will be as an operator

**Comment by ZacLN** [comment]
Are you still unsold on this?

In the same manner, abstract and primitive are not exclusively keywords, they can also be identifiers. I really think that the operator-like properties are dominant for `where`.

**Comment by KristofferC** [comment]
We can go with this for now and revisit later if need be.

**Comment by ZacLN** [comment]
Great, thanks

**Pull request merged**
