### PR TITLE
use github actions instead of travis

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
Why aren't you running?

**Comment by pfitzseb** [comment]
I think you need to put those files into `.github/workflows`, no?

**Comment by KristofferC** [comment]
bild

sigh... thanks :)

**Comment by vtjnash** [comment]
This TagBot.yml file seems to be deprecated now? https://github.com/JuliaLang/Tokenize.jl/actions/runs/597269682

**Pull request merged**
