### PR TITLE
WIP: gen string code for lex_id

### PR DESCRIPTION
**Pull request by ZacLN**
build's `lex_identifier` function code as a string from `KEYWORD` grouped tokens + special cases of `true`, `false`, `in` and `isa`.

### CODE REVIEW

**Comment by KristofferC** [comment]
Out of curiosity, how is the parser going? I'm pretty excited about if it could enable things like code formatting and linting. It is a big job though I guess.

**Comment by ZacLN** [comment]
At the moment it can parse about a 40% of `base\`.

It's got basic formatting output in the form of a vector of corrections for things like: 
+ white space around punctuation (commas, brackets, etc...)
+ symmetric indenting of blocks
+ indent w/ 4 spaces
+ capitalisation of type/module names

I've just about got the framework for linting/all the `vscode-julia` stuff which essentially tracks various scopes thoughout a file so that e.g.
+ assignment operator declares a new variable in the current scope
+ declaring a function initiates a new variable scope (containing all declarations made within the block + function arguments) as well as adding the function name to the current scope
+ tracks offset of all `Expr`s so that location in text can be used to identify the `Token` at any byte offset as well as the telescopic scope (i.e. immediate scope and all parent scopes)

Once this is all in place I think it'll be pretty easy to add the linter as a two stage process: 
1) as the parser steps through the tokens check for local errors (e.g. identically named function arguments, using/import statement inside functions, etc...)
2) a second pass (e.g. checking function calls are to imported/defined functions, all type declarations refer to existing types, etc..)

**Comment by pfitzseb** [comment]
That sounds pretty awesome indeed! Very exciting!

**Comment by ZacLN** [comment]
If you fancy a look it's [here](https://github.com/ZacLN/Parser.jl). It's till a bit wonky but can parse about 80% of `\base` now

```
using Parser
str = readstring(joinpath(Pkg.dir("Tokenize"),"src","lexer.jl"))
x, ps = Parser.parse(str, true) 

# convert to normal AST
Expr(x)

# Formatting hints
ps.hints

# returns: the object, y, at byte 434
#              the stack of expressions that contain it, h
#              the sequence of nodes within these expressions, inds
y, h, inds = find(x, 434);

# Gets the scope at byte position 22514
S = Parser._get_full_scope(x, 22514);

# convert the names/signatures to standard AST, repetitions are where something is overwritten
(x->Expr(x.id)).(S)```

**Comment by KristofferC** [comment]
Very cool. Going bed now but will try it out tomorrow for sure.

**Pull request closed without merging**
