### PR TITLE
Simplify lex_identifier

### PR DESCRIPTION
**Pull request by ZacLN**
Alternative to https://github.com/JuliaLang/Tokenize.jl/pull/187. Simplifies (and speeds up?) lex_identifier by building a hash as each character of an identifier is read and then checking against a table of keywords/word-operators before emiting. However, I'm not sure about the validity of the `simple_hash` function I've used.

Seems to cut timings on the first run to a little more than half with a neglible impact on once-compiled run time for the test below
```julia
for i = 1:5
    run(`julia -e "using Tokenize;@time @eval collect(tokenize(\"foo + bar\"));@time @eval collect(tokenize(\"foo + bar\"));"`)
end
```

### CODE REVIEW

**Comment by KristofferC** [comment]
Nice, https://github.com/JuliaLang/Tokenize.jl/pull/187 still has a quite significant effect though (0.67s -> 0.39s).

**Comment by pfitzseb** [comment]
So why not both? :)

**Comment by KristofferC** [comment]
Seems like the last commit made it worse?

**Comment by ZacLN** [comment]
Hmm. I was testing against a different benchmark (parsing a file) and didn't have the `@eval`, and was seeing improvements. How is the `@eval` influencing the timings?

**Comment by KristofferC** [comment]
If you don't use eval you don't get the full compilation time (things might start compiling before the timing starts).

**Comment by KristofferC** [comment]
Looks like last commit broke something?

**Comment by ZacLN** [comment]
oops - should be fixed now

**Comment by pfitzseb** [comment]
A few timings on my machine:

master:
```
  1.403908 seconds (157.57 k allocations: 8.206 MiB, 100.15% compilation time)
  0.000128 seconds (66 allocations: 4.891 KiB)
```
This PR:
```
  0.732055 seconds (149.31 k allocations: 8.002 MiB, 100.30% compilation time)
  0.000111 seconds (68 allocations: 4.922 KiB)
```
This PR + #187:
```
  0.421957 seconds (149.31 k allocations: 8.001 MiB, 100.53% compilation time)
  0.000132 seconds (68 allocations: 4.922 KiB)
```

So let's get this in ASAP, I think! :)

**Pull request merged**
