### PR TITLE
Add special cstparser token kinds

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by KristofferC** [comment]
Tests for CSTParser fails but that is expected.

**Review by KristofferC — APPROVED** [review]

**Comment by ZacLN** [comment]
Yep, I'm going to try and push new versions of CSTParser/LanguageServer/DocumentFormat today are we all set to tag a release here?

**Comment by KristofferC** [comment]
Yeah, I guess the only problem is if CSTParser does not have an upper bound on Tokenize. Then if we tag this, peoples Tokenize will be updated and their CSTParser will fail. So I guess they need to be tagged at the same time?

**Comment by ZacLN** [comment]
Something like that, I got in trouble with tkleman the last time I made breaking changes. Does it make sense for me to make a minor release on CSTParser adding an upper bound first?

**Comment by KristofferC** [comment]
I think that makes sense, yes.

**Comment by KristofferC** [comment]
But you need to make upper bounds on Tokenize for all previous releases of CSTParser..

**Comment by ZacLN** [comment]
Argggg, does this involve making PRs to METADATA?

**Comment by KristofferC** [comment]
You would have to go `/home/kristoffer/.julia/v0.6/METADATA/CSTParser/versions` and go into each of the folders and change the `requires` so that it has an upper bound, and then PR that to metadata.

**Comment by KristofferC** [comment]
Ok, CSTParser should be taggable now using 0.4 as a lower bound.

**Comment by ZacLN** [comment]
Cheers, I've tagged a version

**Pull request merged**
