### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by pfitzseb**
This now correctly (meaning without emitting `ERROR` tokens) lexes all of current Base 0.5.

The most important of those fixes probably is the one concerned with `'`, since that one could break lexing for the whole remaining file. While caching the last token comes at a small performance cost (<10% for lexing Base, but that could just because of the broken char lexing), I couldn't figure out any other way to do transpose lexing correctly without backtracking (which, at least with `prevind`, doesn't work with `IOStream`s).

`lex_digit` incorrectly tokenized e.g. `2_bessel(...)` -- that fix should be fairly uncontroversial.

The remaining errors were related to `⋅`, which isn't in the list of `UNICODE_OPS` -- I've added it manually for now since I couldn't find a script to generate that file.

### CODE REVIEW

**Comment by KristofferC** [comment]
Very nice, thanks a lot. Now OhMyRepl works nicely with transposes :)

image

**Comment by pfitzseb** [comment]
Great! :)
Are there plans for releasing Tokenize.jl soonish?

**Comment by KristofferC** [comment]
I am basically only using this as a "backend" for OhMyRepl and I won't currently have time to do the whole tagging, setting up travis, writing tests so it gets accepted to METADATA routine. I made you a contributor which I think means that you can register it if you want (which is fine by me). Just ping me if there is anything more I need to do.

**Comment by pfitzseb** [comment]
Alright, fair enough. I'll see what I can do.

About the `UNICODE_OPS` stuff: How'd you generate that list?

**Comment by KristofferC** [comment]
I copied the operators in https://github.com/JuliaLang/JuliaParser.jl/blob/master/src/lexer.jl to a list of chars in a python file then ran

```py
import unicodedata
for s in unicodeops: # <- list of unicode operators
    print(unicodedata.name(s))
```

Where the printing was tweaked a bit. I should be able to find the file on my work computer hopefully.

**Comment by KristofferC** [comment]
Oh well, https://github.com/JuliaLang/METADATA.jl/pull/7276

**Comment by pfitzseb** [comment]
Heh, okay, thanks! :)

(I think I have some unit tests somewhere -- will look into pushing those sometime soon)

**Comment by KristofferC** [comment]
That'd be awesome :)

**Comment by KristofferC** [comment]
Registered :)

**Pull request merged**
