### PR TITLE
Handle more complicated interpolations correctly

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by Keno** [comment]
Ah, I'm wrong here. Somehow I thought commands also had special parser support.

**Comment by Keno** [comment]
Ah, it's a base issue to add that for 1.0: https://github.com/JuliaLang/julia/issues/3150

**Comment by Keno** [comment]
I've updated this to handle the current cmd parsing correctly. We're likely to change the parsing in Base again, but we'll cross that bridge when we get there.

**Comment by KristofferC** [comment]
So, this is ready to be merged now?

**Comment by Keno** [comment]
You're the reviewer, but from my perspective, yes.

**Comment by KristofferC** [comment]
Yeah, I didn't know if "Ah, I'm wrong here. Somehow I thought commands also had special parser support." still applied.

**Comment by Keno** [comment]
No, that's fixed.

**Pull request merged**
