### PR TITLE
fix for underscores in decimal part of floats

### PR DESCRIPTION
**Pull request by ZacLN**
`"1.02_3" was giving: `[FLOAT, IDENTIFIER]`

### CODE REVIEW

**Comment by KristofferC** [comment]
Nice with fixes that removes code :)

**Comment by ZacLN** [comment]
Hmm, not so clever after all, this is treating `_` on its own as a number...

**Comment by KristofferC** [comment]
Did you fix it? Can you add a test that only `_` is not a digit.

**Comment by ZacLN** [comment]
I think so, I uncovered a whole other bunch of errors though

**Comment by ZacLN** [comment]
Alright, I think this catches everything:
+ `_` are not allowed on the boundaries of runs of digits
+ `.01` now parses as a float.

**Pull request merged**
