### PR TITLE
Lex comments as whitespace

### PR DESCRIPTION
**Pull request by ZacLN**
This PR changes the lexer's behaviour to consider comments as white space. I'd argue that from the perspective of the lexer these are equivalent so should be merged.

If you don't fancy this I could try to work this in as an optional setting for the lexer?

### CODE REVIEW

**Comment by KristofferC** [comment]
Hmm, why do you think Python has a `COMMENT` token: https://docs.python.org/2/library/tokenize.html#tokenize.COMMENT?

**Comment by ZacLN** [comment]
I'm not really sure but my guess would be that it's because indentation is used in the syntax so there's a difference between  `["#comment\n", "\t"]` and `"#comment\n\t"` when the tokens are passed to the parser, in the latter case it'll miss the indent and drop out of a block.

**Comment by KristofferC** [comment]
Good point about whitespace sensitivity in Python.

For a syntax highlighter whitespace and comments are not the same though. While not being very likely, a user could for example chose to have a certain background for comments but not on whitespace. In OhMyREPL.jl I have color schemes where the user can chose a certain style for comments but I dont want that to be applied to whitespace. Isn't it easier for the consumer of tokens to treat comments as whitespace if it so chooses?

**Comment by ZacLN** [comment]
That's fine, if you have a use case for which this that make sense then I'll move this downstream. I was only looking at this from a selfish perspective in terms of what I want the parser to get!

**Comment by KristofferC** [comment]
Seems LLVM also has a comment token http://clang.llvm.org/doxygen/group__CINDEX__LEX.html#ggaf63e37eee4280e2c039829af24bbc201a6a24a53d8d4a4aa6e4bcb4847c9652f3.

I think I rather keep the Comment token for now, since I use it for another package, it seems to exist in other languages and dealing with it downstream shouldn't bee too bad.

**Pull request closed without merging**
